### ISSUE TITLE
Authentication by Access Token Missing

### ISSUE THREAD

**Issue by Tob0t** [websms-com/websmscom-php#5]
Currently it is only possible to authenticate by username and password, as our customer want to use this api they would prefer an access-token. Are you planning to provide to authenticate by access token in the near future?

**Comment by reifi** [comment]
The api.websms.com endpoints already support bearer token authentication, but the SDK only supports Basic Auth.
It's not planned to support the whole OAuth2 authentication flow through SDK in near future. 

In the end, it's only a POST request with "Authorization: Bearer <access_token>" as header.
Please seee https://developer.websms.com/rest-api/smsmessaging_text_post
