### ISSUE TITLE
Parameter 'mode' in constructor for class WebSmsCom_Client uses PHP7 style scalar type hinting

### ISSUE THREAD

**Issue by haucap** [websms-com/websmscom-php#7]
The parameter 'mode' in the constructor of the class WebSmsCom_Client uses PHP7 style scalar type hinting, which is not compatible with earlier PHP versions.

Catchable Fatal Error: Argument 4 passed to WebSmsCom_Client::__construct() must be an instance of int, integer given

**Comment by reifi** [comment]
**Thank you very much for your participation!**
I removed the scalar type hinting in the constructor and tested it with PHP 5.0.3+ up to PHP 7.3.7

Get [Release websmscom-php v1.0.7](https://nuget.pkg.github.com/websms-com/websmscom-php/releases/tag/v1.0.7)
